import Client from './client.js';

/**
 * A summarization profile returned by get and list operations, including full configuration details.
 */
export interface Profile {
  /** The unique identifier for this profile, used in profile management API calls and when performing session analysis. */
  id: string;
  /** The display name of the profile. */
  name: string;
  /** The profile's AI configuration. */
  configuration: Omit<ProfileConfiguration, 'llm'>,
  /** The profile's LLM configuration, including prompt instructions and response schema. */
  llm: ProfileLlmOptions,
}

/**
 * Configuration for creating or updating a summarization profile that specifies prompting instructions and session context configuration.
 */
export interface ProfileConfiguration {
  /** AI prompt instructions and output configuration. */
  llm?: ProfileLlmOptions;
  /** Temporal boundaries controlling which portion of the session to analyze. */
  slice?: ProfileSliceOptions;
  /** Session metadata exclusion settings. */
  context?: ProfileContextOptions;
  /** Event data filtering settings. */
  events?: ProfileEventsOptions;
  cache?: {
    /** Enable cached event responses from previous processing requests to be returned, to minimize latency when no new data has been received. */
    enable_event_cache?: boolean,
  }
}

/**
 * Capitalized type identifiers used in response schema definitions.
 * These follow the JSON Schema specification but require capitalized values.
 */
export type ResponseSchemaType = 'OBJECT' | 'ARRAY' | 'STRING' | 'BOOLEAN';

/**
 * A schema node defining the structure of the LLM response.
 *
 * Adheres to the JSON Schema specification with two exceptions:
 * 1. All `type` values must be capitalized (e.g. `OBJECT`, `STRING`, `ARRAY`, `BOOLEAN`).
 * 2. The `$schema` and `$id` properties are not supported and must be omitted.
 *
 * @example
 * ```ts
 * const schema: ResponseSchema = {
 *   type: 'OBJECT',
 *   properties: {
 *     summary: { type: 'STRING', description: 'A brief summary.' },
 *     tags: {
 *       type: 'ARRAY',
 *       items: { type: 'STRING', description: 'A tag.' },
 *     },
 *   },
 *   required: ['summary', 'tags'],
 * };
 * ```
 */
export interface ResponseSchema {
  /** The data type of this schema node. */
  type: ResponseSchemaType;
  /** A description of what this schema node represents, provided as context to the LLM. */
  description?: string;
  /** Property definitions when `type` is `OBJECT`. Each key maps to a nested {@link ResponseSchema}. */
  properties?: Record<string, ResponseSchema>;
  /** Element schema when `type` is `ARRAY`. Defines the structure of each item in the array. */
  items?: ResponseSchema;
  /** Property names that must be present in the LLM response when `type` is `OBJECT`. */
  required?: string[];
}

/**
 * Configuration for the Generative AI large language model, including prompt instructions and output formatting.
 */
export interface ProfileLlmOptions {
  /** Text included in the prompt before the contextual representation of the requested session. */
  pre_prompt?: string,
  /** Custom instructions guiding LLM formatting and content focus, included in the prompt after the session context. */
  post_prompt?: string,
  /** JSON Schema defining the desired JSON structure the LLM should produce. Follows the JSON Schema specification with capitalized type values and without `$schema`/`$id` properties. */
  response_schema?: ResponseSchema,
  /** Controls the randomness of text generated by the large language model. The value is a floating-point number. */
  temperature?: number,
}

/**
 * Controls how events are selected for inclusion in the session context.
 */
export type SliceModeType = 'UNSPECIFIED' | 'FIRST' | 'LAST' | 'TIMESTAMP';

/**
 * Controls which events in the session to analyze.
 */
export interface ProfileSliceOptions {
  /** Slicing strategy that returns the earliest or latest events. Defaults to FIRST. */
  mode?: SliceModeType,
  /** If specified, keeps the number of events if this is greater than zero. */
  event_limit?: number,
  /** If specified, keep events within the specified time duration from the beginning or end time. */
  duration_limit_ms?: number,
  /** If specified, the event limit and duration limit will be applied to the time beginning at this timestamp. */
  start_timestamp?: string,
  /** If specified, only events before this timestamp will be included in the context. */
  end_timestamp?: string,
}

/**
 * Defines session metadata to exclude from processing.
 */
export interface ProfileContextOptions {
  /** Controls the session context elements to exclude, takes precedence over individual inclusion fields. */
  exclude?: ('device' | 'location' | 'org' | 'user')[],
  /** Controls the session context elements to include, takes precedence over individual exclusion fields. */
  include?: ('device' | 'location' | 'org' | 'user')[],
  /** Omits org name, industry, domain, country. */
  exclude_org_context: boolean,
  /** Omits user display name, email, properties. */
  exclude_user_context: boolean,
  /** Omits city, region, country from the session context. */
  exclude_location: boolean,
  /** Omits browser, OS, screen size from the session context. */
  exclude_device: boolean,
}

/**
 * Controls event data handling within summaries.
 */
export interface ProfileEventsOptions {
  /** Event types to exclude from the context. */
  exclude_types?: ('navigate' | 'click' | 'dead-click' | 'error-click' | 'rage-click' | 'input-change' | 'network-error' | 'console-error' | 'mouse-thrash' | 'highlight' | 'copy' | 'paste' | 'element-seen')[],
  /** Event types to include in the context. */
  include_types?: ('navigate' | 'click' | 'dead-click' | 'error-click' | 'rage-click' | 'input-change' | 'network-error' | 'console-error' | 'mouse-thrash' | 'highlight' | 'copy' | 'paste' | 'element-seen')[],
  /** Omits matched defined-event labels from event descriptions. */
  exclude_defined_events?: boolean,
  /** Omits custom API events (type `EVENT_TYPE_CUSTOM`). */
  exclude_api_events?: boolean,
  /** Omits timestamps from all events (events will be present, but the timestamp is not). */
  exclude_event_timestamps?: boolean,
  /** Omits CSS selectors from all events (events will be present, but the selector is not). */
  exclude_selectors?: boolean,
  /** Include display-only tags (`div`, `span`, `body`) in CSS selectors. */
  include_selector_tags?: boolean,
  /** Truncate CSS selectors to the last N elements. */
  trim_to_last_n_selectors: number,
  /** Annotate events with a numeric tab index (1, 2, 3…) for multi-tab sessions. */
  include_tab_index?: boolean,
  /** Include page and element description text from DX Data definitions. */
  include_descriptions: boolean,
}

/**
 * SDK for the Fullstory Summarization Profiles API.
 *
 * Provides methods to create, retrieve, list, update, and delete
 * summarization profiles that control AI session analysis behavior.
 */
export default class SummaryProfileSdk extends Client {

  /**
   * Creates a summarization profile that specifies prompting instructions and session context configuration
   * for use with the session summarize endpoint.
   * See [Create Visit Profile](https://developer.fullstory.com/server/sessions/create-profile/).
   * @param name The display name of the profile.
   * @param configuration Optional configuration including LLM prompts, response schema, slice, context, and events settings.
   * @returns The created `Profile` with its assigned ID.
   */
  async create(name: string, configuration: ProfileConfiguration): Promise<Profile> {
    return this.POST<ProfileConfiguration & { name: string }, Profile>('/v2/visit_profile', {
      ...configuration,
      name,
    });
  }

  /**
   * Returns a single summarization profile by ID.
   * See [Get Visit Profile](https://developer.fullstory.com/server/sessions/get/).
   * @param id The profile ID.
   * @returns The `SummaryProfile` for the given ID.
   */
  async get(id: string): Promise<Profile> {
    return super.GET<Profile>(`/v2/visit_profile/${id}`);
  }

  /**
   * Returns a list of all summarization profiles which specify both prompting instructions and session context configuration.
   * Automatically paginates through all results.
   * See [List Visit Profiles](https://developer.fullstory.com/server/sessions/list-profiles/).
   * @returns An array of all `Profile`.
   */
  async list(): Promise<Profile[]> {
    let profiles: Profile[] = [];
    let paginationToken: string | undefined = undefined;

    do {
      const query: string = paginationToken
        ? `limit=100&pagination_token=${encodeURIComponent(paginationToken)}`
        : 'limit=100';
      const response = await super.GET<{ profiles: Profile[], next_pagination_token?: string }>(`/v2/visit_profile?${query}`);

      profiles = profiles.concat(response.profiles);
      paginationToken = response.next_pagination_token;
    } while (paginationToken);

    return profiles.filter(profile => profile !== undefined).sort((a, b) => (a.name || '').localeCompare(b.name || ''));
  }

  /**
   * Updates an existing summarization profile.
   * See [Update Visit Profile](https://developer.fullstory.com/server/sessions/update/).
   * @param id The profile ID.
   * @param options The profile fields to update.
   * @returns The updated `Profile`.
   */
  async update(id: string, options: Partial<ProfileConfiguration>): Promise<Profile> {
    return this.POST<Partial<ProfileConfiguration>, Profile>(`/v2/visit_profile/${id}`, options);
  }

  /**
   * Deletes a summarization profile.
   * See [Delete Visit Profile](https://developer.fullstory.com/server/sessions/delete/).
   * @param id The profile ID.
   */
  async remove(id: string): Promise<Record<string, never>> {
    return this.DELETE<Record<string, never>>(`/v2/visit_profile/${id}`);
  }
}